
def additoin(x, y):
     print("Addition:", x +b)     
try:
    additoin(10, 20)
except Exception as ve:
    print(ve.__class__)
else:
    print("the operation is successful")
    